export const LOAD_GROUP_DATA = 'LOAD_GROUP_DATA';
export const LOAD_GROUP_DATA_FETCHING = 'LOAD_GROUP_DATA_FETCHING';
export const LOAD_GROUP_DATA_FETCHED = 'LOAD_GROUP_DATA_FETCHED';

export const LOAD_CANDIDATES_DATA = 'LOAD_CANDIDATES_DATA';
export const LOAD_CANDIDATES_DATA_FETCHING = 'LOAD_CANDIDATES_DATA_FETCHING';
export const LOAD_CANDIDATES_DATA_FETCHED = 'LOAD_CANDIDATES_DATA_FETCHED';

export const LOAD_COURTCASES_DATA = 'LOAD_COURTCASES_DATA';
export const LOAD_COURTCASES_DATA_FETCHING = 'LOAD_COURTCASES_DATA_FETCHING';
export const LOAD_COURTCASES_DATA_FETCHED = 'LOAD_COURTCASES_DATA_FETCHED';
