export const LOAD_GROUP_FETCHING = 'LOAD_GROUP_FETCHING';
export const LOAD_GROUP_FETCHED = 'LOAD_GROUP_FETCHED';

export const LOAD_CANDIDATES_FETCHING = 'LOAD_CANDIDATES_FETCHING';
export const LOAD_CANDIDATES_FETCHED = 'LOAD_CANDIDATES_FETCHED';

export const LOAD_COURTCASES_FETCHING = 'LOAD_COURTCASES_FETCHING';
export const LOAD_COURTCASES_FETCHED = 'LOAD_COURTCASES_FETCHED';

export const LOAD_PERSON_DETAILS_FETCHING = 'LOAD_PERSON_DETAILS_FETCHING';
export const LOAD_PERSON_DETAILS_FETCHED = 'LOAD_PERSON_DETAILS_FETCHED';

export const LOAD_CONTRIBUTORS_FETCHING = 'LOAD_CONTRIBUTORS_FETCHING';
export const LOAD_CONTRIBUTORS_FETCHED = 'LOAD_CONTRIBUTORS_FETCHED';

export const LOAD_CONVICTIONS_FETCHING = 'LOAD_CONVICTIONS_FETCHING';
export const LOAD_CONVICTIONS_FETCHED = 'LOAD_CONVICTIONS_FETCHED';

export const LOAD_CHARGES_FETCHING = 'LOAD_CHARGES_FETCHING';
export const LOAD_CHARGES_FETCHED = 'LOAD_CHARGES_FETCHED';
